wiglenet/wigle-wifi-wardriving

- res/values-hu/strings.xml
Removed a couple of repeated strings that were causing warnings.
> remove repeated strings

- res/values-de/strings.xml
> Updated German translation

- wiglewifiwardriving/src/main/res/values-de/strings.xml
I just fixed some translations.
> some fixes for German language variables

- descriptions/de.txt
- wiglewifiwardriving/src/main/res/values-de/strings.xml
Updated the translation of the description file.
Seems like this was previously translated automatically. Horrible grammar. :smiley: 
Hope that this is better now.
> Updated German description translation

- wiglewifiwardriving/src/main/res/values-de/strings.xml
Yet another translation update
> updated German translation, added new variables

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/NewsFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/RankStatsFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/SiteStatsFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/UploadsFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/UserStatsFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/ApiDownloader.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/HttpDownloader.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/HttpFileUploader.java
- wiglewifiwardriving/src/main/res/layout/userstats.xml
Required organizing GET/POST method partition, since all previous requests were performed with POST. Note that this required significant partitioning of connection configuration in HttpFileUploader as well as flowing method throughout the system.
Please review, include critical feedback. Notably, I believe that HttpFileUploader/HttpDownloader were somewhat mis-named even before this PR.
> FEA - cutting news over to new API

- wiglewifiwardriving/src/main/res/layout/rankrow.xml
- wiglewifiwardriving/src/main/res/layout/uploadrow.xml
- wiglewifiwardriving/src/main/res/layout/userstats.xml
Making the stats and upload views match site color schemes, tweaking layout.
> ENH - color and layout tweaks

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/NewsFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/RankStatsFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/SettingsFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/SiteStatsFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/UploadsFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/UserStatsFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/WiGLEAuthException.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/AbstractBackgroundTask.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/ApiDownloader.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/ApiListener.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/BackgroundGuiHandler.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/HttpDownloader.java
re-authenticate if a user changes username or password.
this is accomplished by clearing cached auth user/token and clearing cached files
> BUG - reset tokens on credentials change

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/model/NewsItem.java
> FIX - removing redundant logging

- android-maps-utils/android-maps-utils.iml
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- wiglewifiwardriving/wiglewifiwardriving.iml
Here are some things my dev environment keeps re-including whenever i revert and start developing. they seem innocuous. feel free to reject.
> ENH - build script updates

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/AbstractApiRequest.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/AbstractProgressApiRequest.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/HttpFileUploader.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/ObservationImporter.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/ObservationUploader.java
Refactoring to remove dups and move common network static methods to ApiRequest core (out of upload)
> ENH - refactoring network core

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/AbstractBackgroundTask.java
sometimes a boolean really is just a boolean.
> ENH - preventing accidental taps from cancelling uploads/downloads

- wiglewifiwardriving/src/main/res/drawable/upload_button.xml
- wiglewifiwardriving/src/main/res/layout/list.xml
avoided square corners so it's not TOO Nat-Geo.
> ENH - styling upload button to match site color

- wiglewifiwardriving/src/main/res/layout/userstats.xml
- wiglewifiwardriving/src/main/res/values/strings.xml
trying to make layout more compact - fit on standard screens in vertical layout mode.
> ENH - a little bit of stats-layout cleanup

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ActivateActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/RankStatsFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/TokenAccess.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/UploadsFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/AbstractApiRequest.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/AbstractBackgroundTask.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/AbstractProgressApiRequest.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/FileUploaderTask.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/ObservationUploader.java
First cut at improving token storage using the android keystore system where supported
> ENH - Encrypted token storage

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/SettingsFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/UserStatsFragment.java
- wiglewifiwardriving/src/main/res/layout/settings.xml
- wiglewifiwardriving/src/main/res/values-ar/strings.xml
- wiglewifiwardriving/src/main/res/values-cs/strings.xml
- wiglewifiwardriving/src/main/res/values-da/strings.xml
- wiglewifiwardriving/src/main/res/values-de/strings.xml
- wiglewifiwardriving/src/main/res/values-es/strings.xml
- wiglewifiwardriving/src/main/res/values-fi/strings.xml
- wiglewifiwardriving/src/main/res/values-fr/strings.xml
- wiglewifiwardriving/src/main/res/values-fy/strings.xml
- wiglewifiwardriving/src/main/res/values-he/strings.xml
- wiglewifiwardriving/src/main/res/values-hi/strings.xml
- wiglewifiwardriving/src/main/res/values-hu/strings.xml
- wiglewifiwardriving/src/main/res/values-it/strings.xml
- wiglewifiwardriving/src/main/res/values-ja/strings.xml
- wiglewifiwardriving/src/main/res/values-ko/strings.xml
- wiglewifiwardriving/src/main/res/values-nl/strings.xml
- wiglewifiwardriving/src/main/res/values-nn/strings.xml
- wiglewifiwardriving/src/main/res/values-no/strings.xml
- wiglewifiwardriving/src/main/res/values-pl/strings.xml
- wiglewifiwardriving/src/main/res/values-pt-rBR/strings.xml
- wiglewifiwardriving/src/main/res/values-pt/strings.xml
- wiglewifiwardriving/src/main/res/values-ru/strings.xml
- wiglewifiwardriving/src/main/res/values-sv/strings.xml
- wiglewifiwardriving/src/main/res/values-tr/strings.xml
- wiglewifiwardriving/src/main/res/values-zh/strings.xml
- wiglewifiwardriving/src/main/res/values/strings.xml
Allows explicit "auth" call from settings page after user password entry.
removing stored password on successful auth.
> ENH - allow auth right on the settings page.

- wiglewifiwardriving/src/main/res/layout/rankrow.xml
> ENH- row alignment cleanup

- android-maps-utils/android-maps-utils.iml
- android-maps-utils/build.gradle
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- wiglewifiwardriving/build.gradle
- wiglewifiwardriving/wiglewifiwardriving.iml
> ENH - build updates

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/DatabaseHelper.java
https://github.com/wiglenet/wigle-wifi-wardriving/issues/82
> FIX - #82 and numerous other error reports.

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MappingFragment.java
invert perms check so we can get position when allowed ;)
> FIX - fix for location on map

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/TokenAccess.java
> FIX - uncaught in test build

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/GPSListener.java
Compiler warnings about missing permissions checks + NPE catch (since that's coming from inside google's code.
> FIX - from email, Nexus 6P / 7.1.1 device

- android-maps-utils/android-maps-utils.iml
- build.gradle
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/NewsFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/RankStatsFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/SettingsFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/SiteStatsFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/UploadsFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/UserStatsFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/AbstractApiRequest.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/AbstractProgressApiRequest.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/ObservationImporter.java
- wiglewifiwardriving/wiglewifiwardriving.iml
It's not the right way to handle this, but a production app shouldn't error out because of a sitedown/etc, and we are getting weird error reports.
also, sorry about the build script updates in here, if those are too big a deal, i'll recut.
> FIX - blanket exception handling around JSON elements

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ActivateActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/SettingsFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/AbstractBackgroundTask.java
performing activation unsets "be anonymous" (and thereby removes the activate link) bug report from Raffaele.
> FIX - Hide register link

- wiglewifiwardriving/src/main/res/values-de/strings.xml
> some grammar fixes for German language package

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/DataFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ListFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/AbstractBackgroundTask.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/BackgroundGuiHandler.java
- wiglewifiwardriving/src/main/res/drawable/cancel_button.xml
- wiglewifiwardriving/src/main/res/layout/main.xml
adding a simple cxl button in the inline progress dialog. still results in exception dialogs on cancel (may be delayed in some cases). will need visual refinement, testing
> ENH - adding a cancel button for inline progress

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/DataFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ListFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/BackgroundGuiHandler.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/FileUploaderTask.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/KmlWriter.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/ObservationUploader.java
- wiglewifiwardriving/src/main/res/layout/list.xml
> ENH - Small cleanup and status

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/DataFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/WifiReceiver.java
- wiglewifiwardriving/src/main/res/layout/main.xml
'cause really we don't need this.
also: small layout fix.
> ENH - Scan during upload

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/ApiDownloader.java
- wiglewifiwardriving/src/main/res/layout/main.xml
- wiglewifiwardriving/src/main/res/layout/wigle_detail_toast.xml
tidying toast dlg. background
giving the inline progress bar a title bar
padding adjustments for inline cancellation button
fixing the number of fractional digits on the lat/lon display to 8, to make UI more consistent
> ENH - Ui tweaks

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/UploadsFragment.java
- wiglewifiwardriving/src/main/res/values-ar/strings.xml
- wiglewifiwardriving/src/main/res/values-cs/strings.xml
- wiglewifiwardriving/src/main/res/values-da/strings.xml
- wiglewifiwardriving/src/main/res/values-de/strings.xml
- wiglewifiwardriving/src/main/res/values-es/strings.xml
- wiglewifiwardriving/src/main/res/values-fi/strings.xml
- wiglewifiwardriving/src/main/res/values-fr/strings.xml
- wiglewifiwardriving/src/main/res/values-fy/strings.xml
- wiglewifiwardriving/src/main/res/values-he/strings.xml
- wiglewifiwardriving/src/main/res/values-hi/strings.xml
- wiglewifiwardriving/src/main/res/values-hu/strings.xml
- wiglewifiwardriving/src/main/res/values-ja/strings.xml
- wiglewifiwardriving/src/main/res/values-ko/strings.xml
- wiglewifiwardriving/src/main/res/values-nl/strings.xml
- wiglewifiwardriving/src/main/res/values-nn/strings.xml
- wiglewifiwardriving/src/main/res/values-no/strings.xml
- wiglewifiwardriving/src/main/res/values-pl/strings.xml
- wiglewifiwardriving/src/main/res/values-pt-rBR/strings.xml
- wiglewifiwardriving/src/main/res/values-pt/strings.xml
- wiglewifiwardriving/src/main/res/values-ru/strings.xml
- wiglewifiwardriving/src/main/res/values-sv/strings.xml
- wiglewifiwardriving/src/main/res/values-tr/strings.xml
- wiglewifiwardriving/src/main/res/values-zh/strings.xml
- wiglewifiwardriving/src/main/res/values/strings.xml
> ENH - placeholders for language pack additions of new upload states

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/DataFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/AbstractApiRequest.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/AbstractBackgroundTask.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/ApiDownloader.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/BackgroundGuiHandler.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/ObservationImporter.java
streaming JSON, some cleanups with auth. need to make sure that these are all kosher.
> ENH - new download handling for observation importer.

- wiglewifiwardriving/src/main/AndroidManifest.xml
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/TerminationReceiver.java
from https://wigle.net/phpbb/viewtopic.php?f=3&p=9317#p9317
also removes some old intent handling code in MainActivity
tested using Tasker and adb.
> ENH - allowing a broadcast signal-based app termination

- android-maps-utils/android-maps-utils.iml
- android-maps-utils/build.gradle
- wiglewifiwardriving/build.gradle
- wiglewifiwardriving/src/main/AndroidManifest.xml
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ListFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/TokenAccess.java
- wiglewifiwardriving/wiglewifiwardriving.iml
Handling https://github.com/wiglenet/wigle-wifi-wardriving/issues/155 as well as lineage issue, hopefully.
> migrate to aes in keystore

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MappingFragment.java
> ENH - Tile zoom

- android-maps-utils/AndroidManifest.xml
- android-maps-utils/android-maps-utils.iml
- android-maps-utils/build.gradle
- build.gradle
- wiglewifiwardriving/build.gradle
- wiglewifiwardriving/src/main/AndroidManifest.xml
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/DBResultActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ErrorReportActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/FilterActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MapFilterActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/NetworkActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/SpeechActivity.java
- wiglewifiwardriving/wiglewifiwardriving.iml
Minimum sdk now has to be 14. And had to rename the extended activity.
https://stackoverflow.com/questions/29877692/why-was-actionbaractivity-deprecated
> update to compat 26.0.1, goog-play 11.0.4

- descriptions/fr.txt
French is my mother tongue, so I remade this bad description.
> fix: french description

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ListFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MacFilterActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/NetworkActivity.java
- wiglewifiwardriving/src/main/res/drawable/connect_button.xml
- wiglewifiwardriving/src/main/res/layout/network.xml
- wiglewifiwardriving/src/main/res/values-ar/strings.xml
- wiglewifiwardriving/src/main/res/values-cs/strings.xml
- wiglewifiwardriving/src/main/res/values-da/strings.xml
- wiglewifiwardriving/src/main/res/values-de/strings.xml
- wiglewifiwardriving/src/main/res/values-es/strings.xml
- wiglewifiwardriving/src/main/res/values-fi/strings.xml
- wiglewifiwardriving/src/main/res/values-fr/strings.xml
- wiglewifiwardriving/src/main/res/values-fy/strings.xml
- wiglewifiwardriving/src/main/res/values-he/strings.xml
- wiglewifiwardriving/src/main/res/values-hi/strings.xml
- wiglewifiwardriving/src/main/res/values-hu/strings.xml
- wiglewifiwardriving/src/main/res/values-it/strings.xml
- wiglewifiwardriving/src/main/res/values-ja/strings.xml
- wiglewifiwardriving/src/main/res/values-ko/strings.xml
- wiglewifiwardriving/src/main/res/values-nl/strings.xml
- wiglewifiwardriving/src/main/res/values-nn/strings.xml
- wiglewifiwardriving/src/main/res/values-no/strings.xml
- wiglewifiwardriving/src/main/res/values-pl/strings.xml
- wiglewifiwardriving/src/main/res/values-pt-rBR/strings.xml
- wiglewifiwardriving/src/main/res/values-pt/strings.xml
- wiglewifiwardriving/src/main/res/values-ru/strings.xml
- wiglewifiwardriving/src/main/res/values-sv/strings.xml
- wiglewifiwardriving/src/main/res/values-tr/strings.xml
- wiglewifiwardriving/src/main/res/values-zh/strings.xml
- wiglewifiwardriving/src/main/res/values/strings.xml
allows users to exclude nets from list or logging via the network detail screen.
includes some visual tightening to fit controls and improve readability
> ENH - first pass at on-detail hide/block of network (filter addition)

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/WigleService.java
see ALIBI comment for StackOverflow discussion
> FIX - not elegant, but apparently this is just a thing that happens

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ListFragment.java
> FIX - Scanning indicator fix

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/NetworkActivity.java
- wiglewifiwardriving/src/main/res/layout/network.xml
careless, but I hadn't imagined bssids being < 7 characters.
> FIX - don't offer button with weird/corrupt bssids

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/BackgroundGuiHandler.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/util/WiGLEToast.java
FOR DISCUSSION: heavy-handed, but without a way to reproduce the 7.1 BadTokenExceptions simply, this may be a way...
> FIX - toast replacement, suppress in Android 7.1

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/ObservationUploader.java
MODE_WORLD_READABLE is depr. in M, fails in N.
> FIX - updating file access to supported mode in >= Marshmallow 

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/DataFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/DatabaseHelper.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ListFragment.java
- wiglewifiwardriving/src/main/res/layout/data.xml
- wiglewifiwardriving/src/main/res/values-ar/strings.xml
- wiglewifiwardriving/src/main/res/values-cs/strings.xml
- wiglewifiwardriving/src/main/res/values-da/strings.xml
- wiglewifiwardriving/src/main/res/values-de/strings.xml
- wiglewifiwardriving/src/main/res/values-es/strings.xml
- wiglewifiwardriving/src/main/res/values-fi/strings.xml
- wiglewifiwardriving/src/main/res/values-fr/strings.xml
- wiglewifiwardriving/src/main/res/values-fy/strings.xml
- wiglewifiwardriving/src/main/res/values-he/strings.xml
- wiglewifiwardriving/src/main/res/values-hi/strings.xml
- wiglewifiwardriving/src/main/res/values-hu/strings.xml
- wiglewifiwardriving/src/main/res/values-it/strings.xml
- wiglewifiwardriving/src/main/res/values-ja/strings.xml
- wiglewifiwardriving/src/main/res/values-ko/strings.xml
- wiglewifiwardriving/src/main/res/values-nl/strings.xml
- wiglewifiwardriving/src/main/res/values-nn/strings.xml
- wiglewifiwardriving/src/main/res/values-no/strings.xml
- wiglewifiwardriving/src/main/res/values-pl/strings.xml
- wiglewifiwardriving/src/main/res/values-pt-rBR/strings.xml
- wiglewifiwardriving/src/main/res/values-pt/strings.xml
- wiglewifiwardriving/src/main/res/values-ru/strings.xml
- wiglewifiwardriving/src/main/res/values-sv/strings.xml
- wiglewifiwardriving/src/main/res/values-tr/strings.xml
- wiglewifiwardriving/src/main/res/values-zh/strings.xml
- wiglewifiwardriving/src/main/res/values/strings.xml
per user requests, allow clearing of database
> ENH - Clear db button

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/ObservationUploader.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/PreConnectConfigurator.java
- wiglewifiwardriving/src/main/res/values-ar/strings.xml
- wiglewifiwardriving/src/main/res/values-cs/strings.xml
- wiglewifiwardriving/src/main/res/values-da/strings.xml
- wiglewifiwardriving/src/main/res/values-de/strings.xml
- wiglewifiwardriving/src/main/res/values-es/strings.xml
- wiglewifiwardriving/src/main/res/values-fi/strings.xml
- wiglewifiwardriving/src/main/res/values-fr/strings.xml
- wiglewifiwardriving/src/main/res/values-fy/strings.xml
- wiglewifiwardriving/src/main/res/values-he/strings.xml
- wiglewifiwardriving/src/main/res/values-hi/strings.xml
- wiglewifiwardriving/src/main/res/values-hu/strings.xml
- wiglewifiwardriving/src/main/res/values-it/strings.xml
- wiglewifiwardriving/src/main/res/values-ja/strings.xml
- wiglewifiwardriving/src/main/res/values-ko/strings.xml
- wiglewifiwardriving/src/main/res/values-nl/strings.xml
- wiglewifiwardriving/src/main/res/values-nn/strings.xml
- wiglewifiwardriving/src/main/res/values-no/strings.xml
- wiglewifiwardriving/src/main/res/values-pl/strings.xml
- wiglewifiwardriving/src/main/res/values-pt-rBR/strings.xml
- wiglewifiwardriving/src/main/res/values-pt/strings.xml
- wiglewifiwardriving/src/main/res/values-ru/strings.xml
- wiglewifiwardriving/src/main/res/values-sv/strings.xml
- wiglewifiwardriving/src/main/res/values-tr/strings.xml
- wiglewifiwardriving/src/main/res/values-zh/strings.xml
- wiglewifiwardriving/src/main/res/values/strings.xml
basically stop writing error reports for common networking issues, give people simpler/less alarming error messages. Hopefully cut down on non-actionable error reports.
> ENH - Network error handling; remove complex error messages for common errors.

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/AbstractBackgroundTask.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/BackgroundGuiHandler.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/ObservationUploader.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/PreConnectConfigurator.java
- wiglewifiwardriving/src/main/res/values-ar/strings.xml
- wiglewifiwardriving/src/main/res/values-cs/strings.xml
- wiglewifiwardriving/src/main/res/values-da/strings.xml
- wiglewifiwardriving/src/main/res/values-de/strings.xml
- wiglewifiwardriving/src/main/res/values-es/strings.xml
- wiglewifiwardriving/src/main/res/values-fi/strings.xml
- wiglewifiwardriving/src/main/res/values-fr/strings.xml
- wiglewifiwardriving/src/main/res/values-fy/strings.xml
- wiglewifiwardriving/src/main/res/values-he/strings.xml
- wiglewifiwardriving/src/main/res/values-hi/strings.xml
- wiglewifiwardriving/src/main/res/values-hu/strings.xml
- wiglewifiwardriving/src/main/res/values-it/strings.xml
- wiglewifiwardriving/src/main/res/values-ja/strings.xml
- wiglewifiwardriving/src/main/res/values-ko/strings.xml
- wiglewifiwardriving/src/main/res/values-nl/strings.xml
- wiglewifiwardriving/src/main/res/values-nn/strings.xml
- wiglewifiwardriving/src/main/res/values-no/strings.xml
- wiglewifiwardriving/src/main/res/values-pl/strings.xml
- wiglewifiwardriving/src/main/res/values-pt-rBR/strings.xml
- wiglewifiwardriving/src/main/res/values-pt/strings.xml
- wiglewifiwardriving/src/main/res/values-ru/strings.xml
- wiglewifiwardriving/src/main/res/values-sv/strings.xml
- wiglewifiwardriving/src/main/res/values-tr/strings.xml
- wiglewifiwardriving/src/main/res/values-zh/strings.xml
- wiglewifiwardriving/src/main/res/values/strings.xml
Struggling to find the source of the problems people are seeing with transient login failure. In this instance we were incorrectly describing connection problems as login problems, which this PR fixes.
> FIX - Miscategorized errors

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/BackgroundGuiHandler.java
doesn't get much simpler than this.
> FIX - alternate fix for error messages on upload

- wiglewifiwardriving/src/main/res/values-fr/strings.xml
Adding the missing entries (in the matching spots) to the french translation file. first of many of these.
> ENH - getting at least this translation into form with the full list.

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/TokenAccess.java
I'm confused about how this worked at all.
> FIX - why not just prefer AES?

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MappingFragment.java
- wiglewifiwardriving/src/main/res/layout/map.xml
update map lock-on status when users move the map or tap the "my location" button. lots of experimentation to find a minimal solution, but turned out to be really simple.
> ENH - simplify map control / auto-follow

- wiglewifiwardriving/src/main/AndroidManifest.xml
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/BackgroundGuiHandler.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/ObservationUploader.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/UploadReceiver.java
need to test interactions with enter/exit app, make sure we haven't introduced conflicts in state/uploader.
> ENH - maybe a working background upload intent.

- wiglewifiwardriving/src/main/AndroidManifest.xml
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/RegistrationActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/SettingsFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/WiGLERegistrationInterface.java
- wiglewifiwardriving/src/main/res/layout/activity_registration.xml
first cut at a tighter registration into app - relies on javascript asserted into page and user-agent header.
> ENH - using a webview to integrate registration into app

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MappingFragment.java
just handling the fall-through cleanly when we can't access creds.
> [FIX] - fixing lineage crypto credentials wonkiness in maps.

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ListFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/SettingsFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/GPSListener.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/WifiReceiver.java
- wiglewifiwardriving/src/main/res/layout/settings.xml
- wiglewifiwardriving/src/main/res/values-ar/strings.xml
- wiglewifiwardriving/src/main/res/values-cs/strings.xml
- wiglewifiwardriving/src/main/res/values-da/strings.xml
- wiglewifiwardriving/src/main/res/values-de/strings.xml
- wiglewifiwardriving/src/main/res/values-es/strings.xml
- wiglewifiwardriving/src/main/res/values-fi/strings.xml
- wiglewifiwardriving/src/main/res/values-fr/strings.xml
- wiglewifiwardriving/src/main/res/values-fy/strings.xml
- wiglewifiwardriving/src/main/res/values-he/strings.xml
- wiglewifiwardriving/src/main/res/values-hi/strings.xml
- wiglewifiwardriving/src/main/res/values-hu/strings.xml
- wiglewifiwardriving/src/main/res/values-it/strings.xml
- wiglewifiwardriving/src/main/res/values-ja/strings.xml
- wiglewifiwardriving/src/main/res/values-ko/strings.xml
- wiglewifiwardriving/src/main/res/values-nl/strings.xml
- wiglewifiwardriving/src/main/res/values-nn/strings.xml
- wiglewifiwardriving/src/main/res/values-no/strings.xml
- wiglewifiwardriving/src/main/res/values-pl/strings.xml
- wiglewifiwardriving/src/main/res/values-pt-rBR/strings.xml
- wiglewifiwardriving/src/main/res/values-pt/strings.xml
- wiglewifiwardriving/src/main/res/values-ru/strings.xml
- wiglewifiwardriving/src/main/res/values-sv/strings.xml
- wiglewifiwardriving/src/main/res/values-tr/strings.xml
- wiglewifiwardriving/src/main/res/values-zh/strings.xml
- wiglewifiwardriving/src/main/res/values/strings.xml
quick and dirty prefs-based timeout setting.
> ENH - settable GPS timeouts per #152

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/DBResultActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/NetworkActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/SettingsFragment.java
addressing a spike in stability problems
> FIX - fixing some nullchecks and null objects from bug reports in the play console

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/UploadsListAdapter.java
- wiglewifiwardriving/src/main/res/layout/uploadrow.xml
... because the uploads page wasn't crowded enough
Requires google earth or other KML-viewer (although I can't find a way to detect whether something that can handle KML is present)
> ENH - adding a view button

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/NetworkActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/RegistrationActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/WigleService.java
None of these should be possible - may all be device/version issues.
> FIX - a trio of stability hacks based on play console logs

- TODO
- wiglewifiwardriving/src/main/AndroidManifest.xml
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ListFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/SettingsFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/StartWigleAtBootReciever.java
- wiglewifiwardriving/src/main/res/layout/settings.xml
- wiglewifiwardriving/src/main/res/values-fr/strings.xml
- wiglewifiwardriving/src/main/res/values/strings.xml
Hey!
I've realized this little functionality.
If you think it would be better to do it another way, please, tell me. And if you think it wold be better if it starts in the background and you know how to do it, please tell me.
> feat: Possibility to start Wigle when the phone boot

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/NetworkActivity.java
console doesn't group these, but we've seen several.
> FIX - weird NPE from android console in 2.28.

- android-maps-utils/android-maps-utils.iml
- android-maps-utils/build.gradle
- wiglewifiwardriving/build.gradle
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/TTS.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/WigleService.java
- wiglewifiwardriving/wiglewifiwardriving.iml
Turns out to be more complicated, need to invoke finish on main to get the whole thing to shut down properly. Doing in the service which gets a callback onTaskRemoved when this specific action happens, since doing in onDestroy breaks new app install restart.
> handle when user force kills app

- build.gradle
- wiglewifiwardriving/build.gradle
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/PhoneState.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/WifiReceiver.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/model/MccMncRecord.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/model/Network.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/model/NetworkType.java
This is for discussion, not direct incorporation - this is a really significant rewrite, and requires a great deal of testing and review.
Falls back on old behavior for SDK 14-16 as well as CDMA Phones.
Uses getAllCellInfo on GSM phones SDK 17 and up, maps carrier names from a new hash.
Can detect multiple cells, but currently discards the majority of information from the getAllCells call since it's largely garbage data.
> ENH - A first version of enhanced cell scanning.

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/WifiReceiver.java
new cell logging allowed Integer.MAX_VALUE into signal strengths.
> FIX - fixing signal strength filter for MAX_VALUE

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/NetworkActivity.java
or is it a fix. showing most recent observations. Addresses final element in #229
> ENH - showing latest points to 512 obs limit on net detail

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ListFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/BluetoothReceiver.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/util/BluetoothUtil.java
Doing some cleanup based on previous comments
Fixing a location race condition
> FIX - fixing location race condition for bt scans.

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ListFragment.java
> FIX - fixing wifi counter number

- wiglewifiwardriving/src/main/res/values-de/strings.xml
- wiglewifiwardriving/src/main/res/values-es/strings.xml
- wiglewifiwardriving/src/main/res/values-fi/strings.xml
- wiglewifiwardriving/src/main/res/values-fy/strings.xml
- wiglewifiwardriving/src/main/res/values-hi/strings.xml
- wiglewifiwardriving/src/main/res/values-hu/strings.xml
- wiglewifiwardriving/src/main/res/values-ko/strings.xml
- wiglewifiwardriving/src/main/res/values-nl/strings.xml
- wiglewifiwardriving/src/main/res/values-nn/strings.xml
- wiglewifiwardriving/src/main/res/values-no/strings.xml
- wiglewifiwardriving/src/main/res/values-pl/strings.xml
- wiglewifiwardriving/src/main/res/values-pt-rBR/strings.xml
- wiglewifiwardriving/src/main/res/values-pt/strings.xml
- wiglewifiwardriving/src/main/res/values-ru/strings.xml
- wiglewifiwardriving/src/main/res/values-sv/strings.xml
- wiglewifiwardriving/src/main/res/values-tr/strings.xml
> FIX - more language updates

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/NetworkListAdapter.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/BluetoothReceiver.java
Cleaning up over-aggressive list redraws/sorts. Maybe a little slow, but distinctly better for interaction.
> ENH - reducing list display contention on BT/BLE network updates

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/FilterActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/FilterMatcher.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/NetworkListAdapter.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/BluetoothReceiver.java
per @bobzilladev 's bug report. matching braces is hard.
> FIX - Filter bug

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/NetworkActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/GPSListener.java
- wiglewifiwardriving/src/main/res/layout/network.xml
- wiglewifiwardriving/src/main/res/layout/row.xml
> ENH - adding icons to detail view where applicable.

- wiglewifiwardriving/build.gradle
- wiglewifiwardriving/src/main/AndroidManifest.xml
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/WifiReceiver.java
fixing some of the following cases:
LTE - 00_65535_-1
"WIFI" - 268435455268435455_65535_268435455
"WIFI" - 00_0_0
"WIFI" - 00_65535_-1
"WIFI" - <XXXXX>_1200_-1
"WIFI" -  <XXXXX>_131_-1
"WIFI" -  <XXXXX>_59_-1
"WIFI" - 00_65535_-1
"WIFI" -  <XXXXX>_87_-1
really underscores need for DRY here.
> FIX - fixing some bugs seen in upload cutover to use WCDMA/LTE

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/DBResultActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
per suggestion from @bobzilladev 
also sneaks in some error handling based on errors in play console.
> FIX - Dialog combination for activation of WiFi/BT on startup

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ActivateActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/DBResultActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/DataFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ListFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MappingFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/NetworkActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/BackgroundGuiHandler.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/BluetoothReceiver.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/GPSListener.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/WifiReceiver.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ui/NetworkListAdapter.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ui/NetworkListSorter.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ui/WiGLEToast.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/util/CellNetworkLegend.java
here are a bunch of cleanups and refactors to set the stage for break…ing cell scanning out of the wifireceiver
> ENH - refactors and cleanups

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/WifiReceiver.java
don't want new cell info to reduce reliability. this isn't elegant, but it's unclear what else we can do.
> FIX - one way to mitigate DB unreliability.

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ErrorReportActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/NetworkActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/db/MxcDatabaseHelper.java
since the DB errors are limited to 4.4.x samsung devices.
> FIX - a different approach for fallback

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ErrorReportActivity.java
I'm not sure a 1MB+ stackfile is gonna contain a ton more signal vs. shortening, but here's how we could get it.
> ENH - what if we conditionally attach if the stack's too big to fit in the intent?

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MappingFragment.java
long-running issue with crashes.
#243 in tracker
> FIX - could it be this simple?

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ui/NetworkListAdapter.java
this makes the UI update/interaction a little wonky because of the high update frequency, but it should be safe.
Addressing 3.24 Beta errors in play console.
> FIX - stop trying to batch NetworkListView updates

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/BluetoothReceiver.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ui/NetworkListAdapter.java
flowing "batch" vs. "single net" down into the network add/update. This should be safer, but may not be enough without synchronizing access to the ListView Adapter.
> ENH - one way of doing this. I don't know if this is perfectly safe yet

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/DashboardFragment.java
- wiglewifiwardriving/src/main/res/layout/dashbottom.xml
- wiglewifiwardriving/src/main/res/layout/dashtop.xml
- wiglewifiwardriving/src/main/res/values-ar/strings.xml
- wiglewifiwardriving/src/main/res/values-cs/strings.xml
- wiglewifiwardriving/src/main/res/values-da/strings.xml
- wiglewifiwardriving/src/main/res/values-de/strings.xml
- wiglewifiwardriving/src/main/res/values-es/strings.xml
- wiglewifiwardriving/src/main/res/values-fi/strings.xml
- wiglewifiwardriving/src/main/res/values-fr/strings.xml
- wiglewifiwardriving/src/main/res/values-fy/strings.xml
- wiglewifiwardriving/src/main/res/values-he/strings.xml
- wiglewifiwardriving/src/main/res/values-hi/strings.xml
- wiglewifiwardriving/src/main/res/values-hu/strings.xml
- wiglewifiwardriving/src/main/res/values-it/strings.xml
- wiglewifiwardriving/src/main/res/values-ko/strings.xml
- wiglewifiwardriving/src/main/res/values-nl/strings.xml
- wiglewifiwardriving/src/main/res/values-nn/strings.xml
- wiglewifiwardriving/src/main/res/values-no/strings.xml
- wiglewifiwardriving/src/main/res/values-pl/strings.xml
- wiglewifiwardriving/src/main/res/values-pt-rBR/strings.xml
- wiglewifiwardriving/src/main/res/values-pt/strings.xml
- wiglewifiwardriving/src/main/res/values-ru/strings.xml
- wiglewifiwardriving/src/main/res/values-sv/strings.xml
- wiglewifiwardriving/src/main/res/values-tr/strings.xml
- wiglewifiwardriving/src/main/res/values-zh-rCN/strings.xml
- wiglewifiwardriving/src/main/res/values-zh-rHK/strings.xml
- wiglewifiwardriving/src/main/res/values-zh-rTW/strings.xml
- wiglewifiwardriving/src/main/res/values-zh/strings.xml
- wiglewifiwardriving/src/main/res/values/strings.xml
Using cell color from list view.
Using font size from other top-level elements
Tried to remove "towers" for feedback in languages where that's evident.
> ENH - visual feedback from forums: cell to top, formatting to match BT/WiFi

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/BluetoothReceiver.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ui/NetworkListAdapter.java
Fixing duplicate BT entries in listview (report from forums)
> FIX - dups

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/OkFileUploader.java
confused parameters for upload name/filename
> FIX - fixing filename issue

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ErrorReportActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/BluetoothReceiver.java
> add null checks in ErrorReport and BT Receiver

- wiglewifiwardriving/src/main/res/values-de/strings.xml
Hello,
with the latest update (bluetooth logging) some small translation errors where introduced.
I´m a native german speaker and this changes make more sense to read than the previous ones. 
greetings from Austria,
Stephan
> Update german translation with minor fixes

- wiglewifiwardriving/build.gradle
- wiglewifiwardriving/src/androidTest/java/net/wigle/wigleandroid/NetworkListTest.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/NetworkActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/model/Network.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ui/NetworkListAdapter.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ui/NetworkListUtil.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ui/SetBackedNetworkList.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ui/SetNetworkListAdapter.java
ymmv, but now you can compare them on actual devices.
deduping/DRYing shared elements.
> ENH - first instrumentation performance comparison test between new and old Lists

- wiglewifiwardriving/build.gradle
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
getting un-debuggable error messages
> FIX - Super not called reversal

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/TokenAccess.java
v2 keys would try and decrypt null pref seekrit key
> FIX - don't try and decrypt a null key

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/DashboardFragment.java
- wiglewifiwardriving/src/main/res/layout/dashtop.xml
just visual stuff to make the dashboard more friendly to multiple net types.
> [ENH] - changing up the dashboard for higher info density

- wiglewifiwardriving/build.gradle
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MappingFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/BluetoothReceiver.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ui/SetBackedNetworkList.java
ditching a spurious log message and trying to fix a production null problem.
> FIX - Console error cleanup

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/db/MxcDatabaseHelper.java
stability for older platforms.
> [FIX] - trying to do DB lookups under 4.4 pre 4.4.1 explodes a lot

- wiglewifiwardriving/src/main/res/layout/dashportrait.xml
- wiglewifiwardriving/src/main/res/layout/dashtop.xml
- wiglewifiwardriving/src/main/res/layout/data.xml
- wiglewifiwardriving/src/main/res/layout/list.xml
- wiglewifiwardriving/src/main/res/layout/map.xml
- wiglewifiwardriving/src/main/res/layout/rankrow.xml
- wiglewifiwardriving/src/main/res/layout/uploadrow.xml
- wiglewifiwardriving/src/main/res/values/styles.xml
TIL, move all your custom colors into one place
> ENH - standardizing WiGLE custom colors in preparation for themes

- wiglewifiwardriving/src/main/res/layout/dashlandscape.xml
- wiglewifiwardriving/src/main/res/layout/dashportrait.xml
- wiglewifiwardriving/src/main/res/layout/dashtop.xml
i had broken landscape mode
sending to beta
> [BUG] - Dashboard landscape fix

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
- wiglewifiwardriving/src/main/res/drawable/wigle_menu_item.xml
- wiglewifiwardriving/src/main/res/menu/leftmenu.xml
we had a static reference hanging around that could get replaced.
> FIX - Gps update list fix

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
- wiglewifiwardriving/src/main/res/drawable/wigle_menu_item.xml
- wiglewifiwardriving/src/main/res/menu/leftmenu.xml
braindead mistake. merge this last.
> FIX - Dash tare bug

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ui/SetNetworkListAdapter.java
> [FIX] - fix for NPE

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/WigleService.java
exception on notification when MA is null - from play logs.
> [FIX] accounting for race condition on notification

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- wiglewifiwardriving/src/main/AndroidManifest.xml
> [FIX] - upgrading gradle version. fixing a syntax error it pointed out.

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/ObservationUploader.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/WifiReceiver.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ui/NetworkListUtil.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ui/SetNetworkListAdapter.java
some issues detected in the play dashboard and email
> [FIX] Beta npe fixes

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/DataFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/KmlWriter.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/db/DatabaseHelper.java
nothing has been designed to handle this stuff on our side, by trying to bring implementation into closer alignment with server-side implementation. will probably add `Type:` and `Wifi Networks` folder to server-implementation.
> [ENH] an effort at KML output synchronization between server and client

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/DataFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ListFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/KmlWriter.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/db/DatabaseHelper.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/BluetoothReceiver.java
This should bring the files exported on-device into closer alignment with the new server KML formula (including the app uploads-share), although driving bluetooth off of the contents of the summary table demonstrates that we have a BT GPS problem.
This will lead to two new paths of dev't fixes: 
1. a "share" intent for onboard KML
2. fixes to BT GPS synchronization
> [ENH] adding Cellular and BT folders

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ListFragment.java
navigation drawer selection could get out of sync.
> [FIX] - fixing a minor UI big with quickbutton for map.

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/RankStatsFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/SiteStatsFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/UploadsFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/UserStatsFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/util/MenuUtil.java
fix for #330 - requires making checkable, expanding menu
> [FIX] Making Upload/Stats Fragments shortcut buttons work with the new Nav 

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/BluetoothReceiver.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/WifiReceiver.java
> [FIX] trapping sort errors 

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/GPSListener.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/WifiReceiver.java
not sure about all the consequences of doing this, but it looks safe. review would be greatly appreciated.
> [ENH] here's a naive way of moving lerp into the GPS listener

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
just catching security exception if users say no to bt.
> [FIX] micropr - shouldn't crash.

- android-maps-utils/build.gradle
- wiglewifiwardriving/build.gradle
- wiglewifiwardriving/src/main/AndroidManifest.xml
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ListFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/NetworkActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/GPSListener.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/model/Network.java
- wiglewifiwardriving/src/main/res/layout/network.xml
- wiglewifiwardriving/src/main/res/values-ar/strings.xml
- wiglewifiwardriving/src/main/res/values-nn/strings.xml
- wiglewifiwardriving/src/main/res/values/strings.xml
do not merge, will wait for Q release candidates so api's are locked down.
> changes required for android Q

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/QueryThread.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/db/DatabaseHelper.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/db/MxcDatabaseHelper.java
hard to detect the actual leak sites, but these were places where it *could* happen
> [FIX] more speculative cursor leak prevention

- wiglewifiwardriving/build.gradle
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/DebugActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/BatteryLevelReceiver.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/BluetoothReceiver.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/ScanControlReceiver.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/StartWigleAtBootReciever.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/TerminationReceiver.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/UploadReceiver.java
no proof that this will fix our current stability issues, but some possible culprits addressed
> [FIX] Random stability experiments

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/WigleService.java
not the source of our RSEs, but something we should do anyway.
the majority of the diff is an outer catch block and readability
> [FIX] removing deprecated Icon loading

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/TokenAccess.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/util/InstallUtility.java
fixing 1. jammed mxc implantation on reinstall 2. token jam on upgrade/restore from phone backup
> [FIX] two upgrade errors w/ Pie

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
android makes it hard to add new features while maintaining long-tail compat.
mea culpa.
> [FIX] crashes on older android devices

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/SettingsFragment.java
- wiglewifiwardriving/src/main/res/layout/newsrow.xml
- wiglewifiwardriving/src/main/res/layout/search.xml
- wiglewifiwardriving/src/main/res/layout/settings.xml
Google warns us about usability issues now - these address those warnings.
> [FIX] Usability warnings from gplaycons

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/BluetoothReceiver.java
> [FIX] trapping bt permissions errors

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/UploadsListAdapter.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/BluetoothReceiver.java
if they've navigated away, don't bother.
> [FIX] Kml DL ise

- wiglewifiwardriving/src/main/res/layout/settings.xml
a little extra padding, just like me.
> [ENH] visual padding for settings-screen warning dialog

- android-maps-utils/build.gradle
- wiglewifiwardriving/build.gradle
- wiglewifiwardriving/src/main/AndroidManifest.xml
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ListFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/NetworkActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/BackgroundGuiHandler.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/GPSListener.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/model/Network.java
- wiglewifiwardriving/src/main/res/layout/network.xml
- wiglewifiwardriving/src/main/res/values-ar/strings.xml
- wiglewifiwardriving/src/main/res/values-nn/strings.xml
- wiglewifiwardriving/src/main/res/values/strings.xml
> Changes required for android Q (10)

- wiglewifiwardriving/src/main/AndroidManifest.xml
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ListFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/BluetoothReceiver.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ui/SetBackedNetworkList.java
not perfect, but it makes the display less unreliable. prep for route logging/display with density.
also contains a small feature-detection fix.
> [ENH] Despaz bluetooth display

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/util/FileUtility.java
prevents a one-time error detected in app console.
replaces previous noisy sub-branch.
> [FIX] wrappping freespace check

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
not entirely sure why wrapping a catch block and a null check should result in such a messy diff, but this is just trapping a couple of error cases.
> [FIX] a couple of bug reports.

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/WigleService.java
- wiglewifiwardriving/src/main/res/drawable/ic_w_logo_simple.xml
the planet was always a little busy/complex, vector W works much more cleanly.
including prep work to try and and figure out expanded A10 notifications, but not implemented yet.
> [ENH] swapping in vector W icon for notifications in oreo and up

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/KmlWriter.java
> [FIX] kmlwriter npe from email report

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/DataFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ErrorReportActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/SettingsFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/UploadsFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/UploadsListAdapter.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/AbstractApiRequest.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/BackgroundGuiHandler.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/KmlDownloader.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/KmlWriter.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/ObservationUploader.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/db/DatabaseHelper.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/db/MxcDatabaseHelper.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/util/FileUtility.java
to simplify the coming refactor.
Step 1/3 where
- 2: refactor the code that relies on these interactions
- 3: refit that results to use new file access and sharing mechanisms
> [ENH] step 1: moving file-related constants and methods to a central location

- wiglewifiwardriving/build.gradle
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/BluetoothReceiver.java
> [FIX] removing unused BTLE lib

- wiglewifiwardriving/src/main/res/values-de/strings.xml
dash_new_upload is now clearer and please_allow had a typo.
(im native german speaker)
> small Clarification and typo fix

- CHANGELOG
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/DataFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/db/DatabaseHelper.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/util/FileUtility.java
- wiglewifiwardriving/src/main/res/xml/sqlite_paths.xml
This...seems to work...after a while...android is fun?
> allow internal db backup sharing

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/KmlWriter.java
Hi, I'm Emanuele Iannone, a master student at University of Salerno.
Since my bachelor's thesis I have been working on a **code smell refactoring plugin** called *aDoctor*, which is able to identify and fix energy-related problems in Android apps.
I launched it on your project, finding different instances of code smells. I chose one of them and let the plugin automatically fix it.
In this case I chose Member Ignoring Method, that is present when a non static method does not use at all instance variables and other non static methods. These kind of smell may have a non trivial impact on energy consumption, as shown in this paper: `https://www.sciencedirect.com/science/article/pii/S0950584918301678`.
Besides, this kind of refactoring does not impact on the functionalities of your app, so it …
> Refactor Member Ignoring Method smell in KmlWriter class

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/UploadsFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ui/EndlessScrollListener.java
The old PR was a mess - simplifying for inclusion.
> [ENH] simplifying endless scroll into a new PR

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/db/DatabaseHelper.java
Most of this is feather-burning - these probably have weird external causes / teardown-driven NPEs.
> [FIX] Fix a few exceptions from runtime reports

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/DataFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/util/MagicEightUtil.java
someone had a bad MAC address passed to m8b gen in crashlogs
> [FIX] m8b exception from cluster 25369553

- android-maps-utils/build.gradle
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- wiglewifiwardriving/build.gradle
- wiglewifiwardriving/src/main/AndroidManifest.xml
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/db/DatabaseHelper.java
use requestLegacyExternalStorage crutch for now
> Bump versions

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/SettingsFragment.java
- wiglewifiwardriving/src/main/res/layout/settings.xml
micropr to add version to the settings page - seems to drive people batty having to go to the Play app list.
> [ENH] a simple feature that people really seem to miss: display ver. in app

- build.gradle
- wiglewifiwardriving/build.gradle
OK http upgrade broke android < 5.0 upload.
> [FIX] reverting okhttp prob

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MappingFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/GPSListener.java
- wiglewifiwardriving/src/main/res/layout/map.xml
just add ft/mi or m/km with distance on the map.
also fixes a noise-based distance creep issue in distance recording
> [ENH] superimpose distance on map

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/NetworkActivity.java
- wiglewifiwardriving/src/main/res/layout/network.xml
after using it a bit, it became clear some improvements were necessary.
> [ENH] tiny visual cleanups to make this more legible

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
- wiglewifiwardriving/src/main/res/layout/address_filter_list_item.xml
- wiglewifiwardriving/src/main/res/layout/addressfiltersettings.xml
the play console flags all kinds of crap. most doesn't matter.
> [ENH] Cleanups from play release warnings

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/NetworkActivity.java
bad GPS is bad on the client and the server.
> [FIX] need zero-checks here just like on the server

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
bug report courtesy of 'dd'
only a problem for specific handset ROMs:
https://stackoverflow.com/questions/25830230/android-text-to-speech-throws-activitynotfoundexception
> [ENH] fix for missing TTS intent activity on LG and BBerry Key2

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
Interactive testing in the beta channel. :/
Thanks to dd for helping diagnose these.
> [FIX] clear one non-testable ROM-specific bug, find the next non-testable ROM-specific bug.

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/GPSListener.java
need to get a working release into the world.
> [FIX] disabling all this fancy pending further testing

- wiglewifiwardriving/src/main/AndroidManifest.xml
Tested in android 10, 11. Seems to prevent crash on connect/disconnect from car.
> [FIX] hopefully fixing #379

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ui/NetworkListUtil.java
apparently synthesizing these from vectors in JB2/KitKat hates the new standard.
> [FIX] jb2 and kitkat don't like the observation markers

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/UploadReceiver.java
- wiglewifiwardriving/src/main/res/layout/dashtop.xml
- wiglewifiwardriving/src/main/res/layout/data.xml
Fixing the large-font accessibility issues reported in #460 and #459 .
Fixing an incorrect log message.
> [FIX] accessibility fixes for #460 and #459, fixing an incorrect log message

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
ok, this seems to fix TTS activation AND configuration change.
> [ENH] TTS + configuration change

- descriptions/cs.txt
Added a mention that the release notes and email contact are in English.
"netstumble" and "Keep on stumbling!" do not have counterpart in Czech, so I left them in original.
Also, sorry for two pull requests, I am still learning how to work with Github.
> Manual review of czech translation of description

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ActivateActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/DBResultActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/DataFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ErrorReportActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MappingFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/SearchFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/BackgroundGuiHandler.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/BluetoothReceiver.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/GPSListener.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/WifiReceiver.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ui/WiGLEToast.java
Toast and Dialog presentation apparently causes occasional BadTokenExceptions - this should prevent app termination out from under display of modals.
> [FIX] Bad token prevention

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
defocus current input, hide soft keyboard in side-menu select
> [ENH] quick solution for #470

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/UploadsFragment.java
As reported:
```
java.util.ConcurrentModificationException: 
at java.util.ArrayList$Itr.next (ArrayList.java:860)
at net.wigle.wigleandroid.UploadsFragment$RankDownloadHandler.handleMessage (UploadsFragment.java:282)
at android.os.Handler.dispatchMessage (Handler.java:107)
```
> [FIX] working on fixing concurrentModification issue from play console

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/model/Network.java
Thanks to @ZeroChaos- - removing OWE/Transition from WPA3 tests on client display.
> removing OWE/OWE_TRANSITIONAL from the WPA3 cases.

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/UploadsFragment.java
trying to lock down causes of occasional ConcurrentModification problems with the uploads list.
> [FIX] trying to fix a race condition.

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/NetworkActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ui/ThemeUtil.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/util/SettingsUtil.java
- wiglewifiwardriving/src/main/res/layout-v29/row.xml
- wiglewifiwardriving/src/main/res/layout/row.xml
- wiglewifiwardriving/src/main/res/values-night-v29/colors.xml
- wiglewifiwardriving/src/main/res/values-night-v29/styles.xml
- wiglewifiwardriving/src/main/res/values-v29/colors.xml
- wiglewifiwardriving/src/main/res/values-v29/styles.xml
- wiglewifiwardriving/src/main/res/values/colors.xml
- wiglewifiwardriving/src/main/res/values/styles.xml
some samsung phones aren't respecting light text in list view in night mode. Remedies https://github.com/wiglenet/wigle-wifi-wardriving/issues/475
> [FIX] List view fix

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/KmlWriter.java
set size for undefined set risked NPE.
> [FIX] risk of NPE

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ui/GpxRecyclerAdapter.java
- wiglewifiwardriving/src/main/res/drawable/gpx_selector.xml
- wiglewifiwardriving/src/main/res/layout/gpx_recycler_element.xml
- wiglewifiwardriving/src/main/res/values-it-rIT/strings.xml
- wiglewifiwardriving/src/main/res/values-night-v29/colors.xml
- wiglewifiwardriving/src/main/res/values-v29/colors.xml
- wiglewifiwardriving/src/main/res/values/colors.xml
- we're in the business of storage, not salvation. 
- playtesting makes it clear we need to be able to tell which route we're looking at.
> [ENH] cleanups for GPX browser

- README.md
- wiglewifiwardriving/src/main/res/layout/gpx_recycler_element.xml
Realized that we could answer a lot of questions we get all the time in... the README.
Also a minor layout tweak from new-feature testing.
> [ENH] making the README actually describe the project.

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/GpxManagementActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/model/PolylineRoute.java
- wiglewifiwardriving/src/main/res/layout/activity_gpx_mgmt.xml
like the live run on the Map activity, adds context.
> [ENH] adding distance.

- wiglewifiwardriving/build.gradle
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/BackgroundGuiHandler.java
library version bump and behavior fix from conversation with uhtu
> [FIX] fixing a deps problem and remove-extension fxn

- wiglewifiwardriving/build.gradle
> [FIX] 45 'high' warnings from these two lines, yay

- TODO
so, these were out of date!
Updated, categorized, synced with other TODOs.
Shout out if I removed anything we should have kept or haven't completed as intended
> [ENH] updating very-stale todo

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MappingFragment.java
this is making dynamic mapping look wonky
> [FIX] Route simplification threshold

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/DBResultActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/DataFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MappingFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/NetworkActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/QueryThread.java
Switching from hand-concatenated to parameterized SQL in a quest to improve security and performance.
> [FIX[ Query prepared for network

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/DataFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/RankStatsFragment.java
This little pull request, according to the _TODOs_, implements the missing error toast notifications.
> [ENH] Implementing missing toast notifications

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ListFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MappingFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/GPSListener.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/model/PolylineRoute.java
making the distance calc conditional match route addition - distances will match more closely.
TODO: eliminate low-accuracy jitter (still a problem)
> [ENH] making reported run distance match route distance

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/UserStatsFragment.java
- wiglewifiwardriving/src/main/res/layout/userstats.xml
downloading badge image to add to user stats page- now you can show off your badge to people.
> [ENH] WiGLE.net adding stats badge to the user stats fragment

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ListFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/db/DatabaseHelper.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/BluetoothReceiver.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/GNSSListener.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/WifiReceiver.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/util/CellNetworkLegend.java
Transition to GNSS provider is tickling unjustified route distance increases.
This prevents backtracking based on timestamp problems/race condition weirdness
this is still rough, setting do-not-merge
most of the change is just variable names changes.
> [FIX] first experiment in location -> distance

- wiglewifiwardriving/build.gradle
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ListFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MappingFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/SettingsFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/db/DatabaseHelper.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/db/MxcDatabaseHelper.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/GNSSListener.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/WifiReceiver.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/model/GsmOperator.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ui/ThemeUtil.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ui/WiGLEToast.java
working through legacy cruft and resource management problems that became apparently when upgrading to SDK 31
> [ENH] Modernization

- android-maps-utils/build.gradle
- wiglewifiwardriving/build.gradle
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/TokenAccess.java
> check iv length, bump some versions

- wiglewifiwardriving/src/main/AndroidManifest.xml
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/DBResultActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/NewsFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/NewsListAdapter.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/RankStatsFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/SettingsFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/SiteStatsFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/TokenAccess.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/UploadsFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/UserStatsFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/AbstractProgressApiRequest.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/model/Network.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/model/NewsItem.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/model/RankUser.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/model/Upload.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/model/api/ApiTokenResponse.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/model/api/RankResponse.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/model/api/SiteStats.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/model/api/UploadsResponse.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/model/api/UserStats.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/model/api/WiFiSearchResponse.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/model/api/WiGLENews.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/net/BasicAuthInterceptor.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/net/FileCacheInterceptor.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/net/RequestCompletedListener.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/net/WiGLEApiManager.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/util/FileUtility.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/util/UrlConfig.java
Re-opened due to large change while in-flight.
> [ENH] Network refactor

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ListFragment.java
less service creation, tie into lifecycle
> Executor fix

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/UploadsListAdapter.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/model/Upload.java
> [ENH] queue pos in uploads dispy

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/db/DatabaseHelper.java
- make sure mainAcitivity is still defined before using it to get the template string.
- make sure DB isn't closed before writing a route point.
> [FIX] Race condition fixes

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
Another error from Alpha channel.
> [FIX] npe check

- wiglewifiwardriving/src/main/res/layout/settings.xml
fix for https://github.com/wiglenet/wigle-wifi-wardriving/issues/519 - per https://stackoverflow.com/questions/45442578/scrollview-and-spinner/46964155#46964155 .
> [FIX] fixing arrow-scroll-spinner bug

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ListFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MappingFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/RankStatsFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/util/HeadingManager.java
- null checks from error reports
- full-disabling of heading - it's always junk
- rank stats pagination fix
> [FIX] 271 bug fixes

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/DataFragment.java
> [FIX] responding to missing null check from email

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/RankStatsFragment.java
Fix for #582 - really this time
> [FIX] missing parentheses: still dumb

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ActivateActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/TokenAccess.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/WiGLERegistrationInterface.java
- Force synchronous commit to prefs on token/IV storage
- Force correct prefs load on refresh of API manager
- refresh API manage on auth/reg
> [FIX] token refresh code bug found during testing

- wiglewifiwardriving/src/main/AndroidManifest.xml
> [ENH] making the app resize share screen in new android

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/UploadsListAdapter.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/model/Upload.java
populating and using the 'better' pending number of new-but-location-unknown for in-progress uploads.
> [ENH] Improved Upload New Counts

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/SettingsFragment.java
> [FIX] NPE fix from bug report

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/SettingsFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/AbstractBackgroundTask.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/BackgroundGuiHandler.java
responding to some user reported issues.
> [FIX] fixing some NPE risks

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/DataFragment.java
`baseError: IllegalArgumentException: View=DecorView@76d154e[] not attached to window manager` fixes
> [FIX] safety with the progress dialog

- wiglewifiwardriving/build.gradle
Everything seems to keep working as normal, afaict.
> compile and target 33 to appease goog

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/AbstractListAdapter.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ListFragment.java
hacking a theme-change aware network list view - answering #619
This thing keeps popping back up - mostly SMSN users.
marked Do Not Merge pending further testing
> [FIX] Network list theme loss

- wiglewifiwardriving/src/main/res/layout/list.xml
- wiglewifiwardriving/src/main/res/layout/network.xml
adding some design-time hints, and using them to "ellipsize" two fields which frequently cause runtime layout changes
> [ENH] layout design helpers and two small fixes

- wiglewifiwardriving/src/main/res/layout/dashbottom.xml
- wiglewifiwardriving/src/main/res/layout/dashtop.xml
- wiglewifiwardriving/src/main/res/layout/news.xml
- wiglewifiwardriving/src/main/res/layout/newsrow.xml
- wiglewifiwardriving/src/main/res/layout/rankrow.xml
- wiglewifiwardriving/src/main/res/layout/rankstats.xml
- wiglewifiwardriving/src/main/res/layout/uploadrow.xml
- wiglewifiwardriving/src/main/res/layout/uploads.xml
hey, we can apply this across the board and get visual confirmation of layouts working (or not)
> [ENH] layout defaults everywhere!

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/WigleService.java
some conjunction of target SDK and notification changes was playing a lot of noise -> one star reviews.
> [FIX] notification annoyances

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/WigleService.java
trying to defy system notification BG not working well in SDK 24-29 testing
> [FIX] notification BG / version

- wiglewifiwardriving/src/main/res/layout-v29/map.xml
- wiglewifiwardriving/src/main/res/layout/map.xml
probably never happens to anyone who doesn't have a folding phone
> [ENH] map "starting" text ellipses

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/DBResultActivity.java
unclear how we get empty lat/long pairs but a recorded observation, but we shouldn't crash because of it.
Also specifying char encoding for API GET requests (old call is deprecated)
> [FIX] ISE prevention

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/DBResultActivity.java
showing up rarely, but it's possible
> [FIX] NPE fix from production logs

- wiglewifiwardriving/src/main/res/layout-v29/map.xml
- wiglewifiwardriving/src/main/res/layout/list.xml
- wiglewifiwardriving/src/main/res/layout/map.xml
wish I'd discovered this years ago.
> [ENH] more layout designer hints

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
startup reliability diminished after this change and the new version bump. let's background these loads. Pathology: app would start, but not start scanning, if the user locks the screen, scanning stays stopped until they unlock again. Moving things out of the GUI thread seems like a logical first step in tracing that, and this probably doesn't belong there anyway!
Also minor linting:
- unwrapping an always-true version check
- `@NotNull`ing to match overridden method
> [FIX] take YAML load out of the way of startup

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
From the email
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
at net.wigle.wigleandroid.MainActivity.getBleMfgr(MainActivity.java:2544)
at net.wigle.wigleandroid.model.Network.lookupMfgrByMfgrId(Network.java:362)
at net.wigle.wigleandroid.model.Network.addBleMfgrId(Network.java:312)
at net.wigle.wigleandroid.listener.BluetoothReceiver.addOrUpdateBt(BluetoothReceiver.java:658)
...
> check for some state npe

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/SearchFragment.java
> [FIX] search fix

- build.gradle
- wiglewifiwardriving/build.gradle
> [ENH] small gradle cleanups

- wiglewifiwardriving/src/main/res/layout-v29/map.xml
- wiglewifiwardriving/src/main/res/layout/addressfiltersettings.xml
- wiglewifiwardriving/src/main/res/layout/map.xml
- wiglewifiwardriving/src/main/res/layout/progress_panel_layout.xml
- wiglewifiwardriving/src/main/res/layout/settings.xml
xmas linting - suppressing a couple of warnings and fixing some inefficient layout.
> [FIX] Small layout fixes

- wiglewifiwardriving/build.gradle
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/WigleService.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/net/WiGLEApiManager.java
fixing a 2.8.3 backwards compat for android 7/7.1
> [FIX] fixing android 7 devices broken by new dep.

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ListFragment.java
- wiglewifiwardriving/src/main/res/animator/fade_in_and_out.xml
- wiglewifiwardriving/src/main/res/animator/rotation.xml
- wiglewifiwardriving/src/main/res/animator/rotation_fast.xml
- wiglewifiwardriving/src/main/res/drawable/animated_gps_searching.xml
- wiglewifiwardriving/src/main/res/drawable/gps_searching.xml
- wiglewifiwardriving/src/main/res/layout/list.xml
Trying to make the launch (and GPS-lost) user experience more friendly/intuitive
> [ENH] animated GPS-searching vector

- wiglewifiwardriving/src/main/res/layout-v29/map.xml
- wiglewifiwardriving/src/main/res/layout-v29/row.xml
- wiglewifiwardriving/src/main/res/layout/big_notification_content.xml
- wiglewifiwardriving/src/main/res/layout/dashtop.xml
- wiglewifiwardriving/src/main/res/layout/dbresult.xml
- wiglewifiwardriving/src/main/res/layout/list.xml
- wiglewifiwardriving/src/main/res/layout/map.xml
- wiglewifiwardriving/src/main/res/layout/rankrow.xml
- wiglewifiwardriving/src/main/res/layout/rankstats.xml
- wiglewifiwardriving/src/main/res/layout/row.xml
- wiglewifiwardriving/src/main/res/layout/uploads.xml
- cleaning up layouts, removing redundant weights, fixing content sizes, and improving perf.
- adding existing strings for content description where applicable
probably hard to review this change apart from running it / making sure the strings aptly label the icons.
> [FIX] layout performance and usability fixes

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ui/NetworkListAdapter.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ui/SetNetworkListAdapter.java
- wiglewifiwardriving/src/main/res/layout-v29/row.xml
- wiglewifiwardriving/src/main/res/layout/row.xml
> [FIX] removing manual spacing, because what?

- wiglewifiwardriving/build.gradle
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/net/WiGLEApiManager.java
Confirmed this works on the nexus 5, android `7.1.2`.
> bump certificatetransparency-android to 1.1.1

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/db/DatabaseHelper.java
fixing a production crash by allowing the list to grow after loading
> [FIX] fixed-length -> dynamic array list for service UUIDs

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/ProgressPanelRunnable.java
> [FIX] npe checks on pp handling

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/DBResultActivity.java
really just a race condition, but we have one report.
> [FIX} pretty weird corner case

- .github/workflows/android.yml
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- wiglewifiwardriving/build.gradle
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ErrorReportActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/TokenAccess.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/BackgroundGuiHandler.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/db/MxcDatabaseHelper.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ui/NetworkBubbleDrawable.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ui/NetworkIconGenerator.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ui/WiGLEConfirmationDialog.java
- wiglewifiwardriving/src/main/res/values/strings.xml
adding speculative fixes for dialog-related crashes seen occasionally in reports.
Also upgrade to Gradle 8, which has necessitated two changes:
-  reference changes for Google Maps elements
- configuring BuildConfig.java generation (no longer on by default)
> [FIX] Window disassociation

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/NetworkActivity.java
fix from play console crash log
> [FIX] catching a highly unlikely error on site survey

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/DBResultActivity.java
- wiglewifiwardriving/src/main/res/layout/dbresult.xml
relying on the swipe behavior is wonky.
> [ENH] adding back button to DB result activity.

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/SpeechActivity.java
- wiglewifiwardriving/src/main/res/layout/speech.xml
none of these are perfect, but better.
> [ENH] e2e for speech dlg

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MappingFragment.java
what a strange bug. not refactoring to use MenuHost at this point, but we need to fix that too.
based on a report from NanoTrasen on the forums: https://wigle.net/phpbb/viewtopic.php?t=3363.
> [FIX] fix for menu weirdness

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/AddressFilterAdapter.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/model/OUI.java
- wiglewifiwardriving/src/main/res/layout/address_filter_list_item.xml
- wiglewifiwardriving/src/main/res/layout/addressfiltersettings.xml
Filters are already hard enough to use - why not give people a hint that they got the right OUI?
> [ENH] show the vendor for the OUI prefix for addres filter elements
