- wiglewifiwardriving/src/main/res/values/strings.xml
Change instances of “Wifi” to “”WiFi”. Makes the app consistent
with the Android system and with itself.
Change hyphens to en-dashes in titles.
> Consistently use “WiFi”

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/DataFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ListFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/SettingsFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/AbstractApiRequest.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/ApiDownloader.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/HttpFileUploader.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/ObservationImporter.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/ObservationUploader.java
in order to switch over to QR-based activation, we need everything to use the same API pathway. This is a "light-weight" cutover to the v2 API for uploads without undertaking a deeper rewrite to limit scope and complexity of the change. It's clear that we'll need to further refactor AbstractApiRequest children to bring the observation upload/download functionality into line with the ApiDownload functionality, and DRY everything up. This still requires further edge-case testing, and review. Steps to be taken after this change (not included in this PR):
- move static methods out of HttpFileUploader (and either into their own utility class or into AbstractApiRequest)
- Eliminate vestigial HttpFileUploader and FileUploaderTask
> ENH - upload using the new API

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/UploadsFragment.java
- wiglewifiwardriving/src/main/res/values-ar/strings.xml
- wiglewifiwardriving/src/main/res/values-cs/strings.xml
- wiglewifiwardriving/src/main/res/values-da/strings.xml
- wiglewifiwardriving/src/main/res/values-de/strings.xml
- wiglewifiwardriving/src/main/res/values-es/strings.xml
- wiglewifiwardriving/src/main/res/values-fi/strings.xml
- wiglewifiwardriving/src/main/res/values-fr/strings.xml
- wiglewifiwardriving/src/main/res/values-fy/strings.xml
- wiglewifiwardriving/src/main/res/values-he/strings.xml
- wiglewifiwardriving/src/main/res/values-hi/strings.xml
- wiglewifiwardriving/src/main/res/values-hu/strings.xml
- wiglewifiwardriving/src/main/res/values-it/strings.xml
- wiglewifiwardriving/src/main/res/values-ja/strings.xml
- wiglewifiwardriving/src/main/res/values-ko/strings.xml
- wiglewifiwardriving/src/main/res/values-nl/strings.xml
- wiglewifiwardriving/src/main/res/values-nn/strings.xml
- wiglewifiwardriving/src/main/res/values-no/strings.xml
- wiglewifiwardriving/src/main/res/values-pl/strings.xml
- wiglewifiwardriving/src/main/res/values-pt-rBR/strings.xml
- wiglewifiwardriving/src/main/res/values-pt/strings.xml
- wiglewifiwardriving/src/main/res/values-ru/strings.xml
- wiglewifiwardriving/src/main/res/values-sv/strings.xml
- wiglewifiwardriving/src/main/res/values-tr/strings.xml
- wiglewifiwardriving/src/main/res/values-zh/strings.xml
- wiglewifiwardriving/src/main/res/values/strings.xml
Making the uploads screen display something people can read for status instead of single-letter codes.
> ENH- i18n template values and user-comprehensible strings for upload status

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/DatabaseHelper.java
This change allows the database to be updated based on signal strength as a primary condition, as opposed to a secondary condition to lat/lon changes.
This will cause more updates to occur, but the resulting data will be far more accurate.
Only possible hiccup I could imagine is the LEVEL_CHANGE constant being an int, if update.level is returning a long, the constant may need to be changed to long as well.
> ENH - Allow update based on network strength

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ListFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/SettingsFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/TokenAccess.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/AbstractApiRequest.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/FileUploaderTask.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/ObservationUploader.java
the combination of the last two PRs results in some odd behavior for anonymous uploads. these edits will provide beAnonymous after auth the ability to temporarily anonymize uploads without deauthorizing. This may or may not be a direction we want to go. (the alternative is to clear creds upon setting anonymous, removing all access to profile / stats data, and prevent reversion to authenticated uploads without creds-re-entry, reconfirmation)
> BUG - Fixes and cleanup

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
seeing complaints from users in appstore re: 2.16 lockout due to "overlay detection" during initial permissions requests.
> FIX - marshmallow + toast + permissions dialog = fail

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/DataFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ListFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/SettingsFragment.java
on upload, once you've agreed to use the current user (and you aren't anonymous), we stop hassling you each time. If you deauthorize or change credentials, the dialog appears once more.
next step in background uploading project.
> ENH - adding a preference to prevent continually reconfirming user

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/FilterMatcher.java
one of our most common bugs (between map and list filter regexes) - IllegalArgumentException: utext_close failed: U_ILLEGAL_ARGUMENT_ERROR on  net.wigle.wigleandroid.FilterMatcher.isOk(FilterMatcher.java:46)
**Observed on:**
- LGE w3c (LGL34C) rel. 4.4
- Lenovo  A3300-H (LenovoA3300-H) rel 4.4.2
- Samsung j7ltespr (SM-J700P) rel 6.0.1 
not bubbling this issue to top since filtering is real-time with WiFiReceiver.onReceive (not just on new MapRender() )
> FIX - some native implementations barf on Matcher.reset(charseq).

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/NetworkActivity.java
Common bug report on android versions 4.0 -> 7.0, unable to repro in debugging.
Some notes online indicate that this happens with specific GMS versions, is not fault of use.
Since this shouldn't crash the app, we're trapping and logging, although we'll continue to look for more info
> FIX - just trap this error, since restoring map state isn't really that big a deal

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/DataFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/LegacyObservationImporter.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/ObservationImporter.java
inefficient, but will work for small sets - returns big JSON string, then parses it all in memory (like the bad old days).
This could should be removed as soon as we drop Gingerbread support.
> FIX - creating a gingerbread-friendly Legacy observation import.

- wiglewifiwardriving/src/main/res/layout/settings.xml
- wiglewifiwardriving/src/main/res/values-ar/strings.xml
- wiglewifiwardriving/src/main/res/values-cs/strings.xml
- wiglewifiwardriving/src/main/res/values-da/strings.xml
- wiglewifiwardriving/src/main/res/values-de/strings.xml
- wiglewifiwardriving/src/main/res/values-es/strings.xml
- wiglewifiwardriving/src/main/res/values-fi/strings.xml
- wiglewifiwardriving/src/main/res/values-fr/strings.xml
- wiglewifiwardriving/src/main/res/values-fy/strings.xml
- wiglewifiwardriving/src/main/res/values-he/strings.xml
- wiglewifiwardriving/src/main/res/values-hi/strings.xml
- wiglewifiwardriving/src/main/res/values-hu/strings.xml
- wiglewifiwardriving/src/main/res/values-it/strings.xml
- wiglewifiwardriving/src/main/res/values-ja/strings.xml
- wiglewifiwardriving/src/main/res/values-ko/strings.xml
- wiglewifiwardriving/src/main/res/values-nl/strings.xml
- wiglewifiwardriving/src/main/res/values-nn/strings.xml
- wiglewifiwardriving/src/main/res/values-no/strings.xml
- wiglewifiwardriving/src/main/res/values-pl/strings.xml
- wiglewifiwardriving/src/main/res/values-pt-rBR/strings.xml
- wiglewifiwardriving/src/main/res/values-pt/strings.xml
- wiglewifiwardriving/src/main/res/values-ru/strings.xml
- wiglewifiwardriving/src/main/res/values-sv/strings.xml
- wiglewifiwardriving/src/main/res/values-tr/strings.xml
- wiglewifiwardriving/src/main/res/values-zh/strings.xml
- wiglewifiwardriving/src/main/res/values/strings.xml
breaking settings up into four sections to help people parse the giant list
> ENH - organizing the settings screen into sections

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/GPSListener.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/WifiReceiver.java
Note: there are still toast pop-ups in static contexts, and in:
- BackgroundGuiHandlers
- MappingFragment
- DataFragment
- ActivateActivity
but these are unlikely to overlap on app-exit
> FIX - wrapping the obvious makeText / dead context with isFinishing() tests

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ShareActivity.java
courtesy of crashlytics.
could also simply finish with a nullcheck right after intent is assigned, but slight dup.
> FIX - share activity sometimes gets null intents

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/AbstractBackgroundTask.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/ObservationUploader.java
There may still be some cases where a transfer has completed, but tear down gets called anyway.
> FIX - bug report from user about interruption

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ListFragment.java
from user bug:
> When using the indicator/button to turn scanning on and off, the title changes to "Scan Off" and "Scan On". Using the menu doesn't do that. Also, the text indication is backwards. I've attached a couple of screenshots to demonstrate.
> FIX - bug report on scanning change

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/WigleService.java
- wiglewifiwardriving/wiglewifiwardriving.iml
our minimum sdk level means we don't have to jump through reflection hoops to set up the notification anymore.
> simplify service notification setup. create one even if shutting down

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/DashboardFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/DataFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ErrorReportActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MappingFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/NetworkActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/WigleService.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/TerminationReceiver.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/WifiReceiver.java
Was able to dupe when starting and low-battery path is engaged. This takes care of that path, and changes all cases of MainActivity to finish after a callback, since it's not enough to just call Service.startForeground you actually have to allow time/execution for the notification to be displayed.
Also clean up some MENU_EXIT's that aren't used anymore because they are fragments, and call the notification code in more places in the service just in case that is also a path of RemoteServiceException possibilities.
Android bug: https://issuetracker.google.com/issues/76112072
> switch to finishSoon to try and defeat RemoteServiceException

- build.gradle
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/WigleService.java
Avoid the terrible race condition android built into Context.startForegroundService entirely.
https://issuetracker.google.com/issues/76112072
Should kill the remote service exceptions.
> remove call to startForegroundService and stupid race condition

- etc/mccmncsqlite/01-ddl.sql
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/db/MxcDatabaseHelper.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/WifiReceiver.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/model/GsmOperator.java
per user bug report on pre-lollipop devices; WITHOUT ROWID not valid before SQLite 3.8.2
> FIX - quickfix for older android releases and cell names

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
the display of these dialogs should be contingent upon whether or not we mean to use BT at all.
> FIX - addressing issue from uhtu re spurious dialogs.

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
Bluetooth mostly doesn't explode in testing now; turning on by default.
> [ENH] Turn Bluetooth scanning on by default

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/SettingsFragment.java
default checkbox state will now match default of BT scanning on.
> now that BT defaults to on, bug report from forums

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ListFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ui/SetBackedNetworkList.java
The cause of these issues are probably external / race conditions on start/stop and list change - but that's not reason not to promote stability. Low probability events in any case.
> [FIX] fixing a few errors from the play console 

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
Not sure that this is the cause yet, but it fits the pathology:
- stochastic background process
- broadcast listener
- introduced in 2.44
- can happen without obvious external cause
> [FIX?] seeing whether deregistration of the GNSS listener fixes our RSEs

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
when enabling (disabled at launch-time) WiFi from within the app's pop-up in Android 10, app would go into a zombie scanning/notification mode, leaving the service running after app termination. This should fix that.
> [FIX] cause of hanging process?

- wiglewifiwardriving/build.gradle
- wiglewifiwardriving/src/main/AndroidManifest.xml
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/DataFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ErrorReportActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/SettingsFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/UploadsFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/UploadsListAdapter.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/AbstractApiRequest.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/ApiDownloader.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/BackgroundGuiHandler.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/KmlDownloader.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/KmlWriter.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/ObservationUploader.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/db/DatabaseHelper.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/db/MxcDatabaseHelper.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/util/CsvGzFileProvider.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/util/FileUtility.java
- wiglewifiwardriving/src/main/res/xml/csvgz_paths.xml
All requests involving paths now moved into FileUtility.
DRY'd up SD pathing, error messaging.
Tested in local and external FS mode on Android Pie, for
- Upload KML View
- Database Run KML
- Database DB KML
- Database M8B
- Database CSV RUN
- Database CSV DB
- Database GPX
This is a huge change, and deserves extensive testing.
> [ENH] Centralize FileSystem access - refactor refactor in preparation for Android R

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/db/DatabaseHelper.java
a few NPEs recorded trying to access routes in DB on startup.
> [FIX] check the db before using it. like every other method

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/UploadsFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/UploadsListAdapter.java
Corner case pointed out by @bobzilladev - you *can* share even if the server hasn't processed the file yet.
> [ENH] - once-uploaded, unprocessed button share action

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/DataFragment.java
crash from reporting on `2.51`
```
java.lang.IllegalStateException: Fragment DataFragment{4339e188 (99ef820b-7ce2-4e39-a7fd-9b8ba67fc079)} not attached to a context.
at androidx.fragment.app.Fragment.requireContext(Fragment.java:774)
at androidx.fragment.app.Fragment.getResources(Fragment.java:838)
at androidx.fragment.app.Fragment.getString(Fragment.java:860)
at net.wigle.wigleandroid.DataFragment$BackupTask.onProgressUpdate(DataFragment.java:630)
at net.wigle.wigleandroid.DataFragment$BackupTask.onProgressUpdate(DataFragment.java:542)
```
we COULD try and re-attach to the running activity, but I suspect this is happening when someone shuts the app down or a crash in mid-backup
> [FIX] preventing crash on data fragment detatched

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/model/Network.java
these don't really address RSN-EAP-CCMP yet, but this will be closer.
new paths not exercised yet due to lack of wpa3 nets in test areas.
> altering WPA3 test to include SAE, OWE, EAP_SUITE_B_192

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/DataFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/util/MagicEightUtil.java
converting sipkey hashables to long (avoiding negative ints inherent in signed int32)
Doing this right would involve a test suite.
> [FIX] fixing up hash keys for m8b export

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/DataFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/KmlWriter.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/ObservationUploader.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/util/CsvUtil.java
kinda amazed we didn't receive a report of this sooner.
forcing US ascii dates in files and filenames.
> [FIX] should prevent another unicode-based filename upload crash.

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/NetworkActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ui/NetworkListUtil.java
- wiglewifiwardriving/src/main/res/drawable/observation.xml
- wiglewifiwardriving/src/main/res/layout/search.xml
- wiglewifiwardriving/src/main/res/layout/search_nets.xml
using geo-shape circles in the map network detail created circumstances where zooming in and out would render the observations too small to see or large enough to interfere with the map. (https://github.com/wiglenet/wigle-wifi-wardriving/pull/436 was highlighting this by dynamically zooming in/out) Using markers derived from a vector asset remedies this problem, as well as giving us "click targets" if we want to provide detail of individual observation properties in future releases.
> [ENH] making the map observation markers zoom-proof

- wiglewifiwardriving/src/main/res/values-it/strings.xml
that language has a lot of apostrophes, and for some reason, studio doesn't warn in certain circumstances.
> [FIX] it's always italian.

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ErrorReportActivity.java
collecting more info on some error-email-compose runtime exceptions, lowering the max size a little in hopes of preventing.
> [FIX] stability improvement on crash reporter

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/GPSListener.java
this is an attempt to get a clean UI restart on theme change without breaking everything. some of this is just de-crufting.
- TTS setup was launching on each UI re-instantiation because it was part of setup sound; does the setLocale call above it in onCreate handle this?
- setLocal was being called twice in onCreate (?!)
- adding an atomicBoolean to prevent service termination on a simple UI start; feels like the elaboration of a bad idea, but the alternative is to completely unwire our service management stuff from MainActivity which seems equally fraught
- some linting just because MainActivity is a file that's been through tons of changes over the course of a decade, wanted to see what the real warnings were.
> [FIX] day/night on SDK28+

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
people keep reporting unintended bt-shutdown on exit. Here are some belt-and-suspenders checks.
> [FIX?] getting picky about bt ena/dis per bug reports

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/SpeechActivity.java
remedy for #81 - when TTS checkboxes are "unticked," in-progress TTS is interrupted.
If SSID is the only problem, we *could* limit this to just that checkbox, but this is a simple fix.
> [ENH] interrupt TTS on any TTS option disable

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/DashboardFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ListFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MappingFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/WigleService.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/WifiReceiver.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ui/UINumberFormat.java
Adding distance travelled (in prefs units) to notification element. Allows user to see distance for current program execution without unlocking device.
> [ENH] adding run distance info to notification badge

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/db/DatabaseHelper.java
there's a narrow window in the run loop for DatabaseHelper where a request gets issued, but blows up because we've terminated the app - we can choose not to freak out if the error happened because of asynchrony during shutdown, but I'm not positive that this is a wholly harmless change, would appreciate insight into the original design.
> [FIX] proposed fix for play console exception - needs review

- wiglewifiwardriving/build.gradle
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/BackgroundGuiHandler.java
weeps: can't upgrade commons.io without breaking backwards compat < API 24.
> [FIX] removing vulnerable lib version

- wiglewifiwardriving/build.gradle
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/util/AsyncGpxExportTask.java
using datestamp
also a jackson version bump for security
> [ENH] making export GPX filenames clearer. 

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
if you install in not-an-imperial-units country, default to metric.
> reversing a decade of forcing imperial units on the world.

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/DashboardFragment.java
This small pull request contains one of the changes that appeared in a different [closed pull request](https://github.com/wiglenet/wigle-wifi-wardriving/pull/531). The ```timeString()``` method used for formatting the scan related time duration has been refactored in such a way that it uses ```TimeUnit``` and that the formatted string has an explicit locale (good practices).
> ENH: Dashboard TimeUnit based timeString()

- CHANGELOG
- README.md
- build.gradle
- wiglewifiwardriving/build.gradle
- wiglewifiwardriving/src/main/AndroidManifest.xml
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ActivateActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/DashboardFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ListFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MappingFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/SettingsFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/WigleService.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/db/DatabaseHelper.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/BluetoothReceiver.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/GNSSListener.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/WifiReceiver.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ui/WiGLEToast.java
We bid a fond farewell to SDK versions below 19 with this update.
- targets SDK 31, as required for new play store submission
- splits GPSStatus/GNSSStatus for maximum compat (remains big cleanup target)
- rectifies permission issues for new deployment target (try blocks in BT receiver also a cleanup target)
- fixes start-on-boot Android 10+ (per https://github.com/wiglenet/wigle-wifi-wardriving/issues/435 )
> [FIX] Min sdk updates

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/util/Logging.java
There is a information in the [TODO ](https://github.com/wiglenet/wigle-wifi-wardriving/blob/master/TODO) file to implement logging methods with debug log-level. There are no other implementation details so I interpreted it as follows. I have added two methods which are adapters for ``Android.util.Log`` debug-log methods, just like other methods in the ``Logging`` class. There is also a static field that decides if we will log in debug mode and a ``enableDebugLogging()`` method which can be used to activate debug logging (this method can be called in the application's entrypoint).
> [ENH] Debug logging implementation

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/UploadsFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/UploadsListAdapter.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/model/Upload.java
taking some feedback from previous code review, only to find a bug that needed fixing
- Upload status now uses an enum.
- Previous upload list row behavior hinged on human-readable strings, which was... broken.
- Not sure if there's a more elegant way to translate to human readable but at least this isn't broken.
> [ENH] Upload status <> human readable

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/AddressFilterAdapter.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MacFilterActivity.java
Subtle: you must make a mutable `java.util.ArrayList` from the `java.util.Arrays.ArrayList` before using it in a context where `.remove()` can be called on it!
(per [this post](https://stackoverflow.com/questions/6260113/unsupportedoperationexception-in-abstractlist-remove-when-operating-on-arrayli) )
Some incidental linting.
> [FIX] fixes for pre-release report issues

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/DBResultActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ListFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/AbstractBackgroundTask.java
Some of these null checks are deemed impossible by the linter, but here we are with reports that they've happened
> [FIX] responding to crash reports.

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/DBResultActivity.java
Somehow had an IllegalStateException get out of that catch. Might as well check that there is anything to move to and ignore the move entirely.
> Only move camera if there were results

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/KmlWriter.java
The current approach to filtering the SSID values before appending it to the KML file is to replace certain ranges of the charset. The usage of CDATA can filter most of the [XXE](https://portswigger.net/web-security/xxe) paylods which consist of `<`, `>` and `&` based tags. I found out, that there is still a posibility to inject a payload by escaping from the CDATA tag and then inserting XML/KML tags. To make things clear, this bug **IS NOT** a security vulnerability, but still a bug, which is able to generate a corrupted KML file, what can potentialy lead to *full*/*run* data loss. There is also a small propability that a corrupted KML file can cause problems with third-party applications (very old example: [CVE-2006-7157](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2006-7157)), …
> [FIX] Preventing KML injection via crafted SSID

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/DBResultActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MapRender.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ProgressPanel.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/RankStatsFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/RegistrationActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/UploadsFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/UserStatsFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/net/BasicAuthInterceptor.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ui/AuthenticatedFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ui/GpxRecyclerAdapter.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ui/PrefsBackedCheckbox.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ui/ProgressThrobberFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ui/ThemeUtil.java
Able to condense all but one of the authentication dialog calls.
Also sacrificing unused includes and unreachable version checks to the lint gods./
The remaining `AppCompatActivity` superclass used in `DBResultActivity` doesn't appear easily reconcilable with `FragmentActivity` (we actually use a lot of the functionality in the child class)
> [FIX] Refactor login dialog, lint/cleanup

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/SettingsFragment.java
Saw this on 2.75, going to Try Harder
```
Exception java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context androidx.fragment.app.FragmentActivity.getApplicationContext()' on a null object reference
at net.wigle.wigleandroid.SettingsFragment$1.onTaskFailed (SettingsFragment.java:352)
at net.wigle.wigleandroid.SettingsFragment$1.onTaskFailed (SettingsFragment.java:321)
at net.wigle.wigleandroid.net.WiGLEApiManager$6.onResponse (WiGLEApiManager.java:313)
at okhttp3.internal.connection.RealCall$AsyncCall.run (RealCall.kt:519)
at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1137)
at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:637)
at java.lang.Thread.run (Thread.java:1012)
```
> settings fragment npe

- wiglewifiwardriving/build.gradle
…e Silicon..
Without it ./gradlew build gives:
---------------------------------------------
Build file '/Users/sid/workspace/wigle-wifi-wardriving/wiglewifiwardriving/build.gradle' line: 54
* What went wrong: A problem occurred evaluating project ':wiglewifiwardriving'.
> Could not resolve all files for configuration ':wiglewifiwardriving:driverCopy'.
> Could not find org.xerial:sqlite-jdbc:3.23.3.3.
Searched in the following locations:
- https://dl.google.com/dl/android/maven2/org/xerial/sqlite-jdbc/3.23.3.3/sqlite-jdbc-3.23.3.3.pom
- https://maven.google.com/org/xerial/sqlite-jdbc/3.23.3.3/sqlite-jdbc-3.23.3.3.pom - https://jcenter.bintray.com/org/xerial/sqlite-jdbc/3.23.3.3/sqlite-jdbc-3.23.3.3.pom Required by: project :wiglewifiwardriving
* Try:
> Run with --info or --debug option to …
> Update SQLLite library version to 3.32.3.3 to compile project on Apple Silicon

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/model/Network.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ui/SetNetworkListAdapter.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/util/CellNetworkLegend.java
- wiglewifiwardriving/src/main/res/layout-v29/row.xml
- wiglewifiwardriving/src/main/res/layout/row.xml
- wiglewifiwardriving/src/main/res/values-night-v29/styles.xml
- wiglewifiwardriving/src/main/res/values-v29/styles.xml
- wiglewifiwardriving/src/main/res/values/styles.xml
Now that we're free of some of the older APIs/quirks, we can fix the layout in our list view. This partitions the elements of a row into their own layout cells, rather than pre-composing a long string and putting it into a single second-row cell.
I would prefer that this work in even columss, but the length of WiFi capabilities (building from the "end" of the row) and Cell NetIDs (building from the start) makes  columnar spacing too challenging.
```
+--------------------------------------------------- +
| 310260_14553_21139798   ...                        |
+--------------------------------------------------- +
```
vs wifi, which fills the line completely (and sometimes further)
```
+--------------------------------------------------- +
| 88:00:00:12:00:00  5888MHz  [WPA2][RSN][ESS][WPS] …
```
> [ENH] layout cleanup.

- wiglewifiwardriving/src/main/AndroidManifest.xml
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
https://developer.android.com/reference/android/Manifest.permission#POST_NOTIFICATIONS
This seems to make our notifications work again on api33. Irony that they were so strict about having services have notifications, but now make you opt in to showing them.
> users love approving things, give them POST_NOTIFICATIONS for api33

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ui/WiGLEToast.java
fixes the next leak/exposes MainActivity.state as the next issue
> [FIX] avoiding Toast leak

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MappingFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/GNSSListener.java
common problem during DeadSystemExceptions when the OS is killing things off, as well as a non-serious leak in LeakCanary. Two canaries with one stone?
swaps global application contexts for Activity contexts to avoid race condition (and stops trying to process status updates during shutdown)
> [FIX] trying to eliminate on-shutdown LocationListener leaks

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/DashboardFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/DebugActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/FilterActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/GpxManagementActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MacFilterActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MainActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MapFilterActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/NetworkActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/RegistrationActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/SpeechActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ui/ProgressThrobberActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ui/ScreenChildActivity.java
- wiglewifiwardriving/src/main/res/layout/dashbottom.xml
- wiglewifiwardriving/src/main/res/layout/dashlandscape.xml
- wiglewifiwardriving/src/main/res/layout/dashportrait.xml
- wiglewifiwardriving/src/main/res/layout/dashtop.xml
- wiglewifiwardriving/src/main/res/layout/sitestatslandscape.xml
- wiglewifiwardriving/src/main/res/layout/sitestatsportrait.xml
- wiglewifiwardriving/src/main/res/layout/userstats.xml
getting child activities to follow the MainActivity keep-screen-on state setting.
Addresses https://github.com/wiglenet/wigle-wifi-wardriving/issues/433 - although we should consider making "keep screen on"/"keep screen on while powered" a preference" as a feature request, possibly also allowing intent-based updates.
cleans up redundant/erroneous keepScreenOn XML layout declarations.
> [FIX] screen on behavior inconsistent in child activities

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/WigleService.java
testing confirms bob's assertion that DEFAULT is sufficient with a new or replaced notification channel ID
> [ENH] notification priority fix

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MapRender.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/UploadsFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/model/Upload.java
Allows the uploads screen to self-update on a 30s polling timer if left up, and if user stays on the "first page" of the upload results.
Also a small layout cleanup in map pin caption text.
> [ENH] Upload refresh in progress

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MapRender.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ui/NetworkBubbleDrawable.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ui/NetworkIconGenerator.java
- wiglewifiwardriving/src/main/res/drawable/bt_white.xml
- wiglewifiwardriving/src/main/res/drawable/btle_white.xml
- wiglewifiwardriving/src/main/res/values/dimens.xml
The network rendering behavior has been confusing for a long time.
This is one of a series of improvements to make network type, encryption status, and description more clear during clustering.
This adds:
- Pins colored according to network type
- Text Bubbles colored according to network type
- Icons indicating BT/BLE, 5G vs. other cell, and WiFi encryption status
- defaults to BSSID in the event of empty/null SSID in label.
- increase in labelled-nets from 1/15th to 1/10th of total net cache.
Very open to further refinement, this is just a first step.
> [ENH] Map fragment enhancements

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/SearchFragment.java
- wiglewifiwardriving/src/main/res/layout/search.xml
for some reason, this was absolutely breaking the masked text edit hint.
also threw in some related cleanup on warnings.
> [FIX] fix for recent lyout problems with masked text edit

- wiglewifiwardriving/src/main/res/values/dimens.xml
fixing a minor white space error from refactoring. (vertical spacing on stats submenu)
> [FIX] fixing some spacing defaults for submenu

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/GpxManagementActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/ProgressPanelRunnable.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/UniqueTaskExecutorService.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/util/FileUtility.java
- at-most-one Thread queue was failing to respect job classes
- cache paths were missing a "/"
- added cancel-ability (not yet wired)
> [FIX] for GPX and M8B export thread queue and cache paths

- wiglewifiwardriving/src/main/res/layout-v29/row.xml
- wiglewifiwardriving/src/main/res/layout/address_filter_list_item.xml
- wiglewifiwardriving/src/main/res/layout/checkbox.xml
- wiglewifiwardriving/src/main/res/layout/dash.xml
- wiglewifiwardriving/src/main/res/layout/dashlandscape.xml
- wiglewifiwardriving/src/main/res/layout/list.xml
- wiglewifiwardriving/src/main/res/layout/row.xml
- wiglewifiwardriving/src/main/res/layout/search_nets.xml
- wiglewifiwardriving/src/main/res/layout/sitestatslandscape.xml
- wiglewifiwardriving/src/main/res/layout/wigle_detail_toast.xml
just lint.
- largely making 0dp corresponding Start/Ends explicit.
0 useing the WiGLE service name for the icon in the toast, because I guess that's correct.
> [ENH] making missing start/end padding explicit

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/UserStatsFragment.java
Fixing an actual  issue (leaking static) instead of just linting for once.
Also removing deprecated menu-item layout cmds.
> [FIX] replacing leaking asyncTask

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/AddressFilterAdapter.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MacFilterActivity.java
working through the "correctness" issues with old code.
**Problem:**
"Layout Inflation without a Parent" in compilation report. We're building the row template for the MAC addr filter so that we can re-use it as-needed for each displayed filter row, but failing to pass a parent ViewGroup means that when we translate the XML to ViewGroups/etc, we're not using any device-adapted params. Null "works" but it means we're dynamically resizing at runtime which 1. has a performance cost and 2. may result in display bugs.
[understanding-androids-layoutinflater-inflate](https://bignerdranch.com/blog/understanding-androids-layoutinflater-inflate/)
**Solution:**
[addviewview-layoutparams-is-not-supported](https://stackoverflow.com/questions/4576219/logcat-error-addviewview-layoutparams-is-not-supporte …
> [FIX] fix for null parent

- wiglewifiwardriving/src/main/res/layout/list.xml
Makes layout work better for languages where list_waiting_gps is a long string. Testing in french is a good reminder.
> [ENH]  layout tweak

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/DataFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/GpxManagementActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MappingFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/RankStatsFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/BackupRunnable.java
here's a pass at making all these safe. the only reported exception is in RankStatsFragment which makes this feel a little bit like overkill, but there's reason to believe we're taking this risk in multiple places.
> [FIX] RankStatsFragment ISE fix candidate

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/ProgressPanelRunnable.java
Nothing inside this block makes a difference if the progress panel is null.
> [FIX] ProgressPanelRunnable safety

- wiglewifiwardriving/src/main/res/layout/settings.xml
ui regression caused by linting, reported in #689. added a warning comment.
> [BUG] restoring background hack

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/db/DatabaseHelper.java
didn't know that was a risk here. (from play store report)
checks  NPE:
```
Exception java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
at android.content.ComponentName.<init> (ComponentName.java:131)
at android.content.Intent.<init> (Intent.java:6523)
at net.wigle.wigleandroid.db.DatabaseHelper$DeathHandler.handleMessage (DatabaseHelper.java:292)
```
> [FIX] NPE check

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/GpxManagementActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/db/DatabaseHelper.java
these are almost certainly race conditions/corner cases on shutdown, but might as well check.
> [FIX] Null check route list

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/model/api/CellSearchResponse.java
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.toUpperCase(java.util.Locale)' on a null object reference
at net.wigle.wigleandroid.model.api.CellSearchResponse.asNetwork(CellSearchResponse.java:100)
> fix npe in CellSearchResponse

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/AbstractApiRequest.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/net/WiGLEApiManager.java
fix for https://github.com/wiglenet/wigle-wifi-wardriving/issues/703
filters non-ascii header chars if present in the elements we use to construct the user agent header and DRYs UserAgent generation into the WiGLEApiManager class.
> [FIX] filtering non-safe ASCII header characters from user agent, centralizing

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MappingFragment.java
per https://developers.google.com/maps/documentation/android-sdk/reference/com/google/android/libraries/maps/model/TileProvider#getTile(int,%20int,%20int):
> If you do not wish to provide a tile for this tile coordinate, return [NO_TILE](https://developers.google.com/maps/documentation/android-sdk/reference/com/google/android/libraries/maps/model/TileProvider#NO_TILE). If the tile could not be found at this point in time, return null and further requests might be made with an exponential backoff.
> [ENH] trying a way to get tile retry working

- wiglewifiwardriving/src/androidTest/java/net/wigle/wigleandroid/NetworkListTest.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/DBResultActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ListFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/NetworkActivity.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/SearchFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/db/DatabaseHelper.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/BluetoothReceiver.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/model/Network.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ui/NetworkListAdapter.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ui/NetworkListUtil.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ui/SetNetworkListAdapter.java
Here's a draft of that I've been working on. Notes in-line.
> [ENH/FIX] Search clean-up

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ListFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/MappingFragment.java
- wiglewifiwardriving/src/main/res/drawable/map_layer.xml
Icons have been confusing for a long time.
- switching wrench to filter on ListFragment (since it's the list filtering tool)
- changing map layer from map icon on map fragment
> [ENH] more icon fixes

- wiglewifiwardriving/src/main/res/drawable/map_layer.xml
- wiglewifiwardriving/src/main/res/drawable/search.xml
- wiglewifiwardriving/src/main/res/menu/leftmenu.xml
continuing the move to vector icons in the left menu.
improving rendering for the new layers icon and the sorta-new search icon.
we should continue to eliminate the remaining `ic_menu...` items as possible.
> [ENH] Icon settings

- wiglewifiwardriving/src/main/res/layout/row.xml
Android 7/8 row file needs the BT "random" image area in the layout file too.
> [FIX] Beta bug report: missing random area.

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/ListFragment.java
- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/WifiReceiver.java
```
Exception java.lang.RuntimeException:
at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$1$android-app-LoadedApk$ReceiverDispatcher$Args (LoadedApk.java:1854)
at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run (Unknown Source:2)
at android.os.Handler.handleCallback (Handler.java:942)
at android.os.Handler.dispatchMessage (Handler.java:99)
at android.os.Looper.loopOnce (Looper.java:235)
at android.os.Looper.loop (Looper.java:350)
at android.app.ActivityThread.main (ActivityThread.java:8798)
at java.lang.reflect.Method.invoke
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:703)
at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:911)
Caused by java.lang.NullPointerException:
at …
```
> handle null result, clean up lamestatic init

- wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/NetworkActivity.java
- wiglewifiwardriving/src/main/res/layout/network.xml
we all miss the left-arrow from the now-removed action bar on the network detail screen. shoe-horning it back in next to the SSID and network icon.
Also, adding an option to copy SSID and BSSID with long-press, because maybe those are useful (from user request).
> [ENH] no more bar, but we miss the left arrow
